# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

sudo: required
dist: trusty
services:
  - docker
language: generic
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - willson@robotis.com
env:
  matrix:
#    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=xenial
#    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=bionic
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".dynamixel_workbench.rosinstall" OS_NAME=ubuntu OS_CODE_NAME=xenial
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".dynamixel_workbench.rosinstall" OS_NAME=ubuntu OS_CODE_NAME=bionic
branches:
  only:
    - master
    - develop
    - kinetic-devel
    - melodic-devel
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
