controller_list:
  - name: fake_arm_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: start
  - group: gripper
    pose: place