# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  base_joint:
    has_velocity_limits: true
    max_velocity: 4.01
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 7.01
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_slave_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  rod_left_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  rod_right_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 4.93
    has_acceleration_limits: false
    max_acceleration: 0
  tip_left_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  tip_right_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: false
    max_acceleration: 0