arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - wrist_joint
  gains:
    base_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    shoulder_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    elbow_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_joint:       {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_joint
  gains:
    finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
  